
// 360° = 6.28319 rad
export const FULL_CIRCLE_IN_RADIANS = 6.28319
export const SUN_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / (27 * 24)
export const MERCURY_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / (56.85 * 24)
export const VENUS_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / (-243.025 * 24)
export const EARTH_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / 24
export const MOON_ORBITS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / (27.322 * 24)
export const MARS_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / 24.6
export const JUPITER_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / 9.9
export const SATURN_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / 10.7
export const URANUS_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / 17
export const NEPTUNE_TURNS_IN_HOUR = FULL_CIRCLE_IN_RADIANS / 16.11
export const HOUR_IN_MILLIS = 60 * 60 * 1000